BBBL\LeagueManagerBundle\Entity\Team:
    type: entity
    table: team
    indexes:
        idcoach:
            columns:
                - idcoach
    uniqueConstraints:
        idteamserver:
            columns:
                - idteamserver
    id:
        idteam:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        idroster:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        logo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: Logo_Neutre_00_Player.png
        url:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        idteamserver:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
        prestige:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '1'
        apo:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        assistant:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        pompom:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        tresor:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        reroll:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        popularite:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        urlPhoto:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: url_photo
        proprio:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: 'Non renseigné'
        domicile:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: 'Non renseigné'
        couleurs:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: 'Non renseigné'
        sponsors:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            default: 'Non renseigné'
        gloire:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '100'
        dateModifGloire:
            type: datetime
            nullable: true
            comment: ''
            column: date_modif_gloire
        background:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        cri:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        actif:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
    manyToOne:
        idcoach:
            targetEntity: Membre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcoach:
                    referencedColumnName: idmembre
            orphanRemoval: false
    lifecycleCallbacks: {  }
