BBBL\LeagueManagerBundle\Entity\Membre:
    type: entity
    table: membre
    id:
        idmembre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pseudo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        pass:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: $1$6n..V3/.$uj3Bfs4AKruxej5AMwWW1.
        droits:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        hoverNav:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
            column: hover_nav
        hoverNavPlace:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: hover_nav_place
        tresorerie:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        policeDefaut:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: police_defaut
        actif:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
