BBBL\LeagueManagerBundle\Entity\SaisonLigue:
    type: entity
    table: saison_ligue
    indexes:
        idligue:
            columns:
                - idligue
    uniqueConstraints:
        ordre:
            columns:
                - ordre
    id:
        idsaisonLigue:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idsaison_ligue
            generator:
                strategy: IDENTITY
    fields:
        saison:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
        modeLigue:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
            column: mode_ligue
        ordre:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        dateDeb:
            type: datetime
            nullable: true
            comment: ''
            column: date_deb
        dateFin:
            type: datetime
            nullable: true
            comment: ''
            column: date_fin
        actif:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    manyToOne:
        idligue:
            targetEntity: Ligue
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idligue:
                    referencedColumnName: idligue
            orphanRemoval: false
    lifecycleCallbacks: {  }
