matchs:
    path:     /
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:index" }

matchs_show:
    path:     /{id}/show
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:show" }

matchs_new:
    path:     /new
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:new" }

matchs_create:
    path:     /create
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:create" }
    requirements: { _method: post }

matchs_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:edit" }

matchs_update:
    path:     /{id}/update
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:update" }
    requirements: { _method: post|put }

matchs_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBBLLeagueManagerBundle:Matchs:delete" }
    requirements: { _method: post|delete }
