ligue:
    path:     /
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:index" }

ligue_show:
    path:     /{id}/show/{_format}
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:show", _format: twig }
    requirements: { _format: twig|html|json }

ligue_new:
    path:     /new
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:new" }

ligue_create:
    path:     /create
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:create" }
    requirements: { _method: post }

ligue_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:edit" }

ligue_update:
    path:     /{id}/update
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:update" }
    requirements: { _method: post|put }

ligue_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBBLLeagueManagerBundle:Ligue:delete" }
    requirements: { _method: post|delete }
