saisonligue:
    path:     /
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:index" }

saisonligue_show:
    path:     /{id}/show
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:show" }

saisonligue_new:
    path:     /new
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:new" }

saisonligue_create:
    path:     /create
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:create" }
    requirements: { _method: post }

saisonligue_edit:
    path:     /{id}/edit
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:edit" }

saisonligue_update:
    path:     /{id}/update
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:update" }
    requirements: { _method: post|put }

saisonligue_delete:
    path:     /{id}/delete
    defaults: { _controller: "BBBLLeagueManagerBundle:SaisonLigue:delete" }
    requirements: { _method: post|delete }
